import {SCHEMA,ROLE_NAMES,JOB_FIELDS,clone,uid,blankRow,initialState,employeeName,eligibleEmployees,participantAt,rowHasData,rowActive,calculatedHours,dayHours,monthHours,typeTotals,applyObject,applyRoster,validateRoster,setJobField,applyPaste,basicPay,dayPay} from './model.js';
import {renderMenu,handleMenuChange,handleMenuAction} from './menus.js';

const $=id=>document.getElementById(id);
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=value=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(value);
const STORAGE='work-schedule-demo-v1';
const AUTH='work-schedule-demo-session';
let storageAvailable=true, state=initialState(), undoStack=[], view='schedule', toastTimer;
try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'null');if(saved){if(saved.schema!==SCHEMA||!Array.isArray(saved.days)||saved.days.length!==30||!saved.rates||!saved.positions||!saved.employees||!saved.workTypes||!saved.statuses||!saved.objects||saved.days.some(d=>!Array.isArray(d.rows)||!Array.isArray(d.roster)||!Array.isArray(d.statuses)))throw Error('Invalid data');state=saved;}}catch{storageAvailable=false;}

function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('toast').hidden=true;},4500);}
function status(message){$('save-status').textContent=message;}
function save(){state.revision=uid();try{localStorage.setItem(STORAGE,JSON.stringify(state));storageAvailable=true;status('Сохранено в этом браузере');}catch{storageAvailable=false;status('Не сохранено: хранилище недоступно');toast('Изменения пока только в памяти. Выгрузите XLSX перед закрытием.');}}
function mutate(fn,message){
  try{
    if(storageAvailable){const latest=JSON.parse(localStorage.getItem(STORAGE)||'null');if(latest&&latest.revision!==state.revision){state=latest;render();toast('Данные изменены в другой вкладке. Загружена свежая версия; повторите правку.');return false;}}
    const before=clone(state), next=clone(state);fn(next);state=next;undoStack.push(before);if(undoStack.length>30)undoStack.shift();save();render();if(message)toast(message);return true;
  }catch(error){toast(error.message||'Не удалось применить изменение.');render();return false;}
}
function options(items,value,blank='—'){return `${blank===null?'':`<option value="">${escape(blank)}</option>`}`+items.map(item=>{const val=typeof item==='string'?item:item.value,label=typeof item==='string'?item:item.label;return `<option value="${escape(val)}" ${val===value?'selected':''}>${escape(label)}</option>`;}).join('');}
function employeeOptions(value){const employees=eligibleEmployees(state);const current=state.employees.find(e=>e.id===value);if(current&&!employees.some(e=>e.id===value))employees.push(current);return options(employees.map(e=>({value:e.id,label:e.name+(!e.active?' (неактивен)':'')})),value);}
function fieldLabel(field){return {time:'Время',invoice:'Счет',pay:'ЗП за смену',adjustment:'Штрафы и премии',shiftHours:'Часов за смену',objectId:'Номер объекта',type:'Вид работ',hours:'Часов на бригаду',object:'Объект',phone:'Телефон работ',objectNotes:'Примечания по объекту',task:'ТЗ на работы',notes:'Примечания по работам',tech:'Техбаза'}[field]||ROLE_NAMES[Number(field.replace('person',''))];}
function attributes(day,row,field){return `data-day="${day.date}" data-row="${row.id}" data-field="${field}" aria-label="${escape(fieldLabel(field))}, ${Number(day.date.slice(-2))} сентября, строка ${day.rows.indexOf(row)+1}"`;}
function input(day,row,field,value,{type='text',placeholder='',className='',title=''}={}){const limits=type==='number'?(field==='hours'?'min="0" max="24" step="0.25"':field==='shiftHours'?'min="0" max="1000" step="0.25"':`min="${field==='adjustment'?-10000000:0}" max="10000000" step="1"`):'';return `<input class="cell-input ${className}" ${attributes(day,row,field)} type="${type}" value="${escape(value??'')}" placeholder="${escape(placeholder)}" title="${escape(title)}" ${limits} ${type==='text'?'maxlength="5000"':''}>`;}
function textarea(day,row,field,value,className=''){return `<textarea class="cell-input ${className}" ${attributes(day,row,field)} maxlength="5000" rows="2" placeholder="—">${escape(value)}</textarea>`;}
function select(day,row,field,value,items,blank='—'){return `<select class="cell-input" ${attributes(day,row,field)}>${options(items,value,blank)}</select>`;}
function selectedDays(){const filter=$('day-filter').value;return state.days.filter(d=>filter==='all'||filter==='demo'&&d.date<='2026-09-03'||filter===d.date);}
function dayTitle(day){const date=new Date(day.date+'T12:00:00');return `${date.getDate()} сентября`;}
function renderDay(day,index){
  const collapsed=state.collapsedDays.includes(day.date), n=day.rows.filter(rowActive).length;
  const weekday=new Intl.DateTimeFormat('ru-RU',{weekday:'long'}).format(new Date(day.date+'T12:00:00'));
  let html=`<tr class="date-row ${index%2?'alt-day':''}"><td colspan="18"><div class="date-sticky"><button class="icon-button" data-collapse-day="${day.date}" aria-label="${collapsed?'Развернуть':'Свернуть'} ${dayTitle(day)}" aria-expanded="${!collapsed}">${collapsed?'▸':'▾'}</button><strong class="date-number">${dayTitle(day)}</strong><span class="date-weekday">${weekday}</span><span class="date-summary">${n} работ · ${num(dayHours(day))} ч${day.hoursOverride!==null?' (вручную)':''}</span><button class="day-add" data-add-rows="${day.date}">＋ 2 строки</button></div></td></tr>`;
  if(collapsed)return html;
  const rosterCell=(indices,cls)=>`<td class="shift-member ${cls}">${indices.map(i=>`<select data-shift-person="${i}" data-day="${day.date}" aria-label="${ROLE_NAMES[i]} смены, ${dayTitle(day)}">${employeeOptions(day.roster[i])}</select><select class="status-select" data-shift-status="${i}" data-day="${day.date}" aria-label="Статус: ${ROLE_NAMES[i]}, ${dayTitle(day)}">${options(state.statuses.map(s=>({value:s.code,label:s.code})),day.statuses[i])}</select>`).join('')}</td>`;
  html+=`<tr class="shift-row"><td class="shift-label">СОСТАВ<br>И СТАТУС</td>${rosterCell([0],'lead')}${rosterCell([1],'partner')}${rosterCell([2],'extra')}${rosterCell([3,4],'extra')}<td colspan="13" class="shift-tip">Состав смены можно изменить. В работу подставляются сотрудники со статусами РД и ДЕЖ.<br>В ячейке сотрудника можно убрать участие. Пустой расчетный итог возвращает автоматический расчет.</td></tr>`;
  day.rows.forEach((row,r)=>{
    const memberCell=(indices,cls)=>`<td class="job-member ${cls}">${indices.map(i=>{const auto=row.type&&['РД','ДЕЖ'].includes(day.statuses[i])?day.roster[i]:'';return `<select class="cell-input" ${attributes(day,row,`person${i}`)} title="Сотрудник из состава смены; можно убрать участие">${options([{value:'__auto',label:employeeName(state,auto)||'— автоматически'},...(day.roster[i]?[{value:day.roster[i],label:employeeName(state,day.roster[i])}]:[])],row.people[i]===null?'__auto':row.people[i],'— не участвует')}</select>`;}).join('')}</td>`;
    const missing=!row.type&&rowHasData(row);
    html+=`<tr class="job-row ${r%2?'alt-job':''}" data-job-id="${row.id}"><td class="time-cell">${input(day,row,'time',row.time,{type:'time'})}</td>${memberCell([0],'lead-cell')}${memberCell([1],'partner-cell')}${memberCell([2],'extra-cell')}${memberCell([3,4],'extra-cell')}<td>${select(day,row,'invoice',row.invoice,state.invoiceStates)}</td>`;
    if(r===0){html+=`<td rowspan="${day.rows.length}" class="money-cell">${input(day,row,'pay',dayPay(state,day),{type:'number',title:'Базовая сумма ставок. Очистите ячейку, чтобы вернуть расчет.'})}<span class="${day.pay===null?'sum-label':'manual-label'}">${day.pay===null?'по ставкам<br>без доплат':'вручную'}</span></td><td rowspan="${day.rows.length}" class="money-cell adjust-cell">${input(day,row,'adjustment',day.adjustment,{type:'number',placeholder:'—'})}<span class="sum-label">− штраф<br>+ премия</span></td><td rowspan="${day.rows.length}" class="shift-total">${input(day,row,'shiftHours',dayHours(day),{type:'number',title:'Сумма часов работ. Очистите ячейку, чтобы вернуть расчет.'})}<span class="${day.hoursOverride===null?'sum-label':'manual-label'}">${day.hoursOverride===null?'Σ часов':'вручную'}</span></td>`;}
    html+=`<td>${select(day,row,'objectId',row.objectId,state.objects.map(o=>({value:o.id,label:o.id+' · '+o.name})))}</td><td class="${missing?'invalid':''}">${select(day,row,'type',row.type,state.workTypes.map(t=>({value:t.code,label:t.code})))}${missing?'<span class="missing-marker">Выберите вид</span>':''}</td><td>${input(day,row,'hours',row.hours,{type:'number',placeholder:'—'})}</td><td>${textarea(day,row,'object',row.object,'object-title')}</td><td>${textarea(day,row,'phone',row.phone)}</td><td>${textarea(day,row,'objectNotes',row.objectNotes,'object-addition')}</td><td>${textarea(day,row,'task',row.task)}</td><td>${textarea(day,row,'notes',row.notes,'work-notes')}</td><td><div class="tech-wrap">${input(day,row,'tech',row.tech,{placeholder:'https://…'})}${/^https?:\/\//i.test(row.tech)?`<a href="${escape(row.tech)}" class="tech-link" target="_blank" rel="noopener noreferrer" aria-label="Открыть техбазу">↗</a>`:''}</div></td></tr>`;
  });return html;
}
function render(){
  const focused=document.activeElement;const focusKey=focused?.dataset.field?{day:focused.dataset.day,row:focused.dataset.row,field:focused.dataset.field}:null;
  const scroll=document.querySelector('.table-scroll'),top=scroll.scrollTop,left=scroll.scrollLeft;
  $('total-hours').textContent=num(monthHours(state));
  const count=state.days.reduce((n,d)=>n+d.rows.filter(rowActive).length,0);
  $('total-description').textContent=`${count} работ · ${state.days.filter(d=>d.rows.some(rowActive)).length} смен с заданиями`;
  document.querySelectorAll('[data-roster]').forEach(el=>{el.innerHTML=employeeOptions(state.roster[Number(el.dataset.roster)]);});
  $('sheet-name').textContent=`Б1 + ${employeeName(state,state.roster[0])||'Бригадир'} + ${employeeName(state,state.roster[1])||'Осн. напарник'}`;
  $('schedule-body').innerHTML=state.monthCollapsed?'':selectedDays().map(renderDay).join('');
  scroll.hidden=state.monthCollapsed;document.querySelector('.sheet-hint').hidden=state.monthCollapsed;
  $('collapse-month').textContent=state.monthCollapsed?'▸':'▾';$('collapse-month').setAttribute('aria-expanded',String(!state.monthCollapsed));$('collapse-month').setAttribute('aria-label',state.monthCollapsed?'Развернуть месяц':'Свернуть месяц');
  const allCollapsed=selectedDays().every(d=>state.collapsedDays.includes(d.date));$('collapse-days').textContent=allCollapsed?'Развернуть дни':'Свернуть дни';
  $('type-totals').innerHTML=typeTotals(state).map(([type,hours])=>`<div class="type-total" title="${escape(state.workTypes.find(t=>t.code===type)?.label||type)}"><span>${escape(type)}</span><strong>${num(hours)} ч</strong></div>`).join('')||'<span class="muted">Пока нет часов по видам работ</span>';
  $('undo').disabled=!undoStack.length;
  if(!storageAvailable)status('Хранилище недоступно или данные повреждены — экспортируйте изменения');
  scroll.scrollTop=top;scroll.scrollLeft=left;
  if(focusKey){const target=[...$('schedule-body').querySelectorAll('[data-field]')].find(el=>el.dataset.day===focusKey.day&&el.dataset.row===focusKey.row&&el.dataset.field===focusKey.field);target?.focus({preventScroll:true});}
  if(view!=='schedule')$('directory-view').innerHTML=renderMenu(state,view);
}
function navigate(next){view=next;$('schedule-view').hidden=next!=='schedule';$('directory-view').hidden=next==='schedule';document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===next);if(b.dataset.view===next)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(next!=='schedule')$('directory-view').innerHTML=renderMenu(state,next);}
function login(){ $('login-view').hidden=true;$('app-view').hidden=false;render(); }
$('login-form').addEventListener('submit',event=>{event.preventDefault();if($('login').value==='admin'&&$('password').value==='admin'){try{sessionStorage.setItem(AUTH,'demo');}catch{}$('login-error').hidden=true;login();}else{$('login-error').textContent='Неверный логин или пароль. Для демо используйте admin / admin.';$('login-error').hidden=false;}});
$('toggle-password').addEventListener('click',()=>{const hidden=$('password').type==='password';$('password').type=hidden?'text':'password';$('toggle-password').setAttribute('aria-label',hidden?'Скрыть пароль':'Показать пароль');});
$('logout').addEventListener('click',()=>{try{sessionStorage.removeItem(AUTH);}catch{}document.querySelectorAll('dialog[open]').forEach(d=>d.close());$('app-view').hidden=true;$('login-view').hidden=false;$('password').value='admin';$('login').focus();});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
$('day-filter').innerHTML+=state.days.map(d=>`<option value="${d.date}">${dayTitle(d)}</option>`).join('');
$('day-filter').addEventListener('change',render);
$('collapse-month').addEventListener('click',()=>mutate(s=>{s.monthCollapsed=!s.monthCollapsed;}));
$('collapse-days').addEventListener('click',()=>{const dates=selectedDays().map(d=>d.date),expand=dates.every(d=>state.collapsedDays.includes(d));mutate(s=>{s.collapsedDays=expand?s.collapsedDays.filter(d=>!dates.includes(d)):[...new Set([...s.collapsedDays,...dates])];});});
$('apply-roster').addEventListener('click',()=>{const roster=[...document.querySelectorAll('[data-roster]')].map(el=>el.value),from=$('period-from').value,to=$('period-to').value;let count=0;if(mutate(s=>{count=applyRoster(s,roster,from,to);}))toast(`Состав применен: ${count} смен. Период ${from.slice(-2)}–${to.slice(-2)} сентября.`);});
$('schedule-body').addEventListener('click',event=>{const collapse=event.target.closest('[data-collapse-day]'),add=event.target.closest('[data-add-rows]');if(collapse)mutate(s=>{const date=collapse.dataset.collapseDay;s.collapsedDays=s.collapsedDays.includes(date)?s.collapsedDays.filter(d=>d!==date):[...s.collapsedDays,date];});if(add)mutate(s=>{s.days.find(d=>d.date===add.dataset.addRows).rows.push(blankRow(),blankRow());s.collapsedDays=s.collapsedDays.filter(d=>d!==add.dataset.addRows);},'Добавлены две строки.');});
$('schedule-body').addEventListener('change',event=>{const el=event.target,date=el.dataset.day;if(!date)return;
  if(el.dataset.field){if(el.checkValidity&&!el.checkValidity()){el.reportValidity();return;}mutate(s=>{const day=s.days.find(d=>d.date===date),row=day.rows.find(r=>r.id===el.dataset.row);setJobField(s,day,row,el.dataset.field,el.value);});}
  else if(el.dataset.shiftPerson!==undefined){const i=Number(el.dataset.shiftPerson);mutate(s=>{const day=s.days.find(d=>d.date===date),roster=[...day.roster];roster[i]=el.value;validateRoster(s,roster);day.roster=roster;day.statuses[i]=el.value?'РД':'';day.rows.forEach(r=>r.people[i]=null);});}
  else if(el.dataset.shiftStatus!==undefined){const i=Number(el.dataset.shiftStatus);mutate(s=>{const day=s.days.find(d=>d.date===date);if(el.value&&!day.roster[i])throw Error('Сначала выберите сотрудника смены.');day.statuses[i]=el.value;});}
});
$('schedule-body').addEventListener('paste',event=>{const el=event.target;if(!el.dataset.field)return;const text=event.clipboardData.getData('text/plain');if(!text.includes('\t')&&!(el.tagName!=='TEXTAREA'&&text.trimEnd().includes('\n')))return;event.preventDefault();const day=state.days.find(d=>d.date===el.dataset.day),index=day.rows.findIndex(r=>r.id===el.dataset.row),column=JOB_FIELDS.indexOf(el.dataset.field==='person4'?'person3':el.dataset.field);if(column<0){toast('Вставьте диапазон начиная с основной ячейки строки.');return;}mutate(s=>applyPaste(s,day.date,index,column,text),'Диапазон вставлен.');});
$('schedule-body').addEventListener('keydown',event=>{const el=event.target;if(!el.dataset.field)return;if(event.key==='Escape'){event.preventDefault();render();el.blur();return;}if(event.key==='Enter'&&el.tagName!=='TEXTAREA'){event.preventDefault();el.blur();return;}if(event.key==='Tab'){
  const controls=[...$('schedule-body').querySelectorAll('input,select,textarea')],index=controls.indexOf(el),next=controls[index+(event.shiftKey?-1:1)];if(!next)return;event.preventDefault();const identity={field:next.dataset.field,row:next.dataset.row,day:next.dataset.day,person:next.dataset.shiftPerson,status:next.dataset.shiftStatus};el.blur();queueMicrotask(()=>{const fresh=[...$('schedule-body').querySelectorAll('input,select,textarea')].find(n=>n.dataset.day===identity.day&&n.dataset.field===identity.field&&n.dataset.row===identity.row&&n.dataset.shiftPerson===identity.person&&n.dataset.shiftStatus===identity.status);fresh?.focus();});
}});
$('undo').addEventListener('click',()=>{if(!undoStack.length)return;try{const latest=JSON.parse(localStorage.getItem(STORAGE)||'null');if(latest&&latest.revision!==state.revision){state=latest;undoStack=[];render();toast('Данные изменились в другой вкладке. История отмены очищена.');return;}}catch{}state=undoStack.pop();save();render();toast('Последнее изменение отменено.');});
$('reset').addEventListener('click',()=>$('reset-dialog').showModal());
$('confirm-reset').addEventListener('click',()=>{const before=clone(state);state=initialState();undoStack.push(before);save();render();$('reset-dialog').close();toast('Начальные данные восстановлены.');});
$('export').addEventListener('click',async()=>{const button=$('export');button.disabled=true;button.textContent='Подготовка XLSX…';try{const snapshot=clone(state);const {downloadXlsx}=await import('./download-xlsx.js');await downloadXlsx(snapshot);toast('Книга XLSX готова: график, сотрудники и справочники.');}catch(error){toast(error.message||'Не удалось создать файл Excel.');}finally{button.disabled=false;button.textContent='↓ Экспорт XLSX';}});
$('help').addEventListener('click',()=>$('help-dialog').showModal());
document.querySelectorAll('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
$('add-work').addEventListener('click',()=>{const filter=$('day-filter').value;$('new-day').innerHTML=state.days.map(d=>`<option value="${d.date}">${dayTitle(d)}</option>`).join('');$('new-day').value=filter.startsWith('2026-')?filter:'2026-09-01';$('new-type').innerHTML=options(state.workTypes.map(t=>({value:t.code,label:`${t.code} — ${t.label}`})),'ЧВ',null);$('new-object').innerHTML=options(state.objects.map(o=>({value:o.id,label:`${o.id} · ${o.name}`})),'','Без объекта / переезд');$('add-dialog').showModal();});
$('add-form').addEventListener('submit',event=>{event.preventDefault();const date=$('new-day').value;if(mutate(s=>{const day=s.days.find(d=>d.date===date);let row=day.rows.find(r=>!rowActive(r));if(!row){day.rows.push(blankRow(),blankRow());row=day.rows.at(-2);}setJobField(s,day,row,'type',$('new-type').value);setJobField(s,day,row,'time',$('new-time').value);setJobField(s,day,row,'hours',$('new-hours').value);if($('new-object').value)applyObject(s,row,$('new-object').value);s.monthCollapsed=false;s.collapsedDays=s.collapsedDays.filter(d=>d!==date);})){$('add-dialog').close();$('day-filter').value=date;render();toast('Работа добавлена в график.');}});
$('directory-view').addEventListener('change',event=>mutate(s=>handleMenuChange(s,event.target)));
$('directory-view').addEventListener('click',event=>{const action=event.target.closest('[data-menu-action]');if(action)mutate(s=>handleMenuAction(s,action));});
window.addEventListener('storage',event=>{if(event.key!==STORAGE||!event.newValue)return;try{const updated=JSON.parse(event.newValue);if(updated.schema===SCHEMA){state=updated;undoStack=[];render();toast('График обновлен из другой вкладки.');}}catch{toast('Не удалось прочитать изменения из другой вкладки.');}});
document.querySelector('.help-list').innerHTML=`<li>В шапке выберите сотрудников группы «Поля» и период. «Применить» заменит состав этих смен, а новым сотрудникам поставит РД. Состав каждой смены можно изменить отдельно.</li><li>В задания подставляется состав смены при статусах РД или ДЕЖ и заполненном виде работ. Имя в задании можно убрать или вернуть. Часы сотрудника учитывают только его задания.</li><li>Редактируйте все ячейки с данными. Вид, статус, счет и сотрудники проверяются по справочникам, в том числе при вставке диапазона из Excel. Tab переводит в следующую ячейку, Enter завершает правку, Escape отменяет незавершенный ввод.</li><li>Стрелки у месяца и дня сворачивают строки. «+ 2 строки» расширяет смену. Пустые дни уже созданы до конца сентября; выберите «Весь месяц», чтобы их увидеть.</li><li>Номер объекта подставляет название, контакт, примечание и ТЗ. Поля можно дополнить вручную. Изменение справочника обновляет связанные поля заданий; ручные дополнения сохраняются.</li><li>Зарплата — предварительная сумма базовых ставок по часам каждого сотрудника с учетом водителя и отпуска; доплаты бригадиру, обучение, штрафы и премии в нее не включены. Для остальных статусов ставка в демо равна нулю. Условия расчета нужно согласовать для рабочей версии.</li><li>Расчетные часы и зарплату можно заменить вручную: появится пометка «вручную». Очистите ячейку, чтобы вернуть формулу. Справочник ставок используется в базовом расчете сразу.</li><li>Меню «Сотрудники» и «Справочники» содержит редактируемые списки. В демо вымышленные люди и объекты. XLSX содержит график, сотрудников и справочники с цветами и группировкой строк. Значения сохраняются как снимок на момент выгрузки.</li><li>Все изменения сохраняются только в текущем браузере. Вход admin/admin демонстрационный; совместная работа и защищенная авторизация требуют сервера PHP.</li>`;
try{if(sessionStorage.getItem(AUTH)==='demo')login();}catch{}
render();
